#!/usr/bin/env bash
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

SALT=`date | shasum -a 256 | cut -c1-8`
VERSION_TAG=cpu-${SALT}
IMAGE_TAG=gcr.io/kubeflow-rl/kubeflow-rl-baselines:cpu-b54052a2
LOG_DIR=/tmp/${SALT}
COMMAND="python3 -m baselines.ppo2.run_atari"

docker run --workdir /app \
  -it ${IMAGE_TAG} \
  $COMMAND
